# Written by Dr Jodie Wetherall <wj88@gre.ac.uk>, School of Engineering, University of Greenwich
#
# This file is intended to support OO bindings to the OpenRAVE API. It assumes
# the same licencing scheme as OpenRAVE.
#
# OpenRAVE is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "prototypes.idl"

[function, scriptable, uuid(545BC716-18E6-4179-9A34-76BAF5A74F61)]
interface ICallback : nsISupports {
	void Invoke();
};

[function, scriptable, uuid(B8244B49-9340-48F7-969A-5C75B76EE47D)]
interface ICallbackUserCheck : nsISupports {
	boolean Invoke();
};
